### PR TITLE
open-json version is updated

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by inaiat** [comment]
Solomax, can I release this update?

**Comment by solomax** [comment]
I believe so :) According to @tdunning it contains bug fixes only :)))

**Comment by tdunning** [comment]
On Tue, Dec 13, 2016 at 6:48 AM, Maxim Solodovnik <notifications@github.com>
wrote:

> I believe so :) According to @tdunning <https://github.com/tdunning> it
> contains bug fixes only :)))
>
>
Yes. But those bug fixes may affect assumptions that wicket makes.
Adversely.

**Comment by solomax** [comment]
Actually 1.6 is bundled into wicket 6.x and 7.x, and added as dependency to 8.x
Please see https://github.com/apache/wicket/pull/193#issuecomment-266437274
I can additionally check wicketstuff-jqplot ....

**Pull request merged**
